### ISSUE TITLE
REST calls should return result information

### ISSUE THREAD

**Issue by achorein** [jrrdev/mantisbt-sync-core#1]
You got no response when you call a REST service :

for example :

```
curl -X POST 'http://localhost:8080/batch/operations/jobs/syncEnumsJob' --data "jobParameters=mantis.username=foo,mantis.password=foopasswd"
```

You shoud get an http response with some JSON data like : status, exit code, message

Hard to debug at this time (failing silently)

**Comment by jrrdev** [comment]
Jobs are launched asynchronously so the only response you get is the execution id.
But in the REST API, there are endpoint to monitor the jobs (exit status, logs etc...).
Documentation have been added in the Readme because [Codecentric's spring-boot-starter-batch-web](https://github.com/codecentric/spring-boot-starter-batch-web)  isn't really great...
